name = "PseudospectralCollocOCP"
uuid = "81ab4503-8523-4da9-a0e7-e0223415609c"
authors = ["Stepan Oslejsek"]
version = "1.0.0-DEV"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
FastGaussQuadrature = "1.1.0"
Ipopt = "1.13.0"
JuMP = "1.29.3"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
